name: MaxKreutzer
favicon: null
layout_spectrum: 0.8900527239311486
typography_spectrum: 0.5726587001699954
title: Shells and Space
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cacaca'
    - '#8d8d8d'
    - '#626260'
    - '#40413c'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.8795724643860012
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
